[server]
enableCORS = false
maxUploadSize = 5

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false

[client]
caching = true
showErrorDetails = false